-- Add last_modified to products table if not exists
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS last_modified TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- Create product_price_history table
CREATE TABLE IF NOT EXISTS public.product_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    old_purchase_price DECIMAL(10, 2),
    new_purchase_price DECIMAL(10, 2),
    old_selling_price DECIMAL(10, 2),
    new_selling_price DECIMAL(10, 2),
    changed_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Add RLS policies for product_price_history
ALTER TABLE public.product_price_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.product_price_history FOR SELECT USING (true);
CREATE POLICY "Enable insert access for authenticated users only" ON public.product_price_history FOR INSERT WITH CHECK (auth.role() = 'authenticated');
