-- Migration 039: Product model number is generated, HSN/SAC removed
-- Product identity is now controlled by product_model_rules and generated by the app.

ALTER TABLE products
    DROP COLUMN IF EXISTS hsn_code;

CREATE UNIQUE INDEX IF NOT EXISTS idx_products_model_number
    ON products(model_number)
    WHERE model_number IS NOT NULL AND model_number <> '';

NOTIFY pgrst, 'reload schema';
