-- Create voucher_types table
CREATE TABLE IF NOT EXISTS voucher_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    company_id BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE voucher_types ENABLE ROW LEVEL SECURITY;

-- Create basic RLS policies for voucher_types
CREATE POLICY "Allow public read of voucher_types"
    ON voucher_types FOR SELECT
    USING (true);

CREATE POLICY "Allow public insert of voucher_types"
    ON voucher_types FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow public update of voucher_types"
    ON voucher_types FOR UPDATE
    USING (true);

CREATE POLICY "Allow public delete of voucher_types"
    ON voucher_types FOR DELETE
    USING (true);

-- Insert default voucher types
INSERT INTO voucher_types (name, description) VALUES
('Payment', 'Record payment transactions'),
('Receipt', 'Record receipt transactions'),
('Contra', 'Record bank/cash transfer transactions'),
('Journal', 'Record adjustment/non-cash entries'),
('Sales', 'Record sales transactions'),
('Purchase', 'Record purchase transactions'),
('Credit Note', 'Record sales return transactions'),
('Debit Note', 'Record purchase return transactions')
ON CONFLICT (name) DO NOTHING;
